[tool.black]
line-length = 120
target-version = ['py38', 'py39', 'py310', 'py311', 'py312']


[tool.pytest.ini_options]
testpaths = [
    "test",
]


[build-system]
requires = ["setuptools>=65.0.0", "wheel", "cython"]
build-backend = "setuptools.build_meta"
